#!/usr/bin/perl

### BEGIN INIT INFO
# Provides:          supertuxkart
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: supertuxkart service 1.0
# Description:       supertuxkart service 1.0
# Documentation:     https://gameplayer.club
# Type:              forking
# X-Interactive:     false
### END INIT INFO

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 1, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

my $SUPERTUXKARTDIR = "/root/SuperTuxKart";

my $Command = $ARGV[0];
if ($Command eq "")
{
	$Command = "NONE";
}

my $running=`ps ax|grep SuperTuxKart|grep -v grep`;

if ($Command eq "start")
{
	if ($running eq "")
	{
		print "Starting Super Tux Kart...\n";
		if (-f "$SUPERTUXKARTDIR/nostart")
		{
			print "Removing $SUPERTUXKARTDIR/nostart\n";
			# Remove the lock file if it exists
			unlink("$SUPERTUXKARTDIR/nostart");
		}
		# Start the screen process
		system("nohup $SUPERTUXKARTDIR/startsupertuxkart > /tmp/SuperTuxKartStartup.log\&");
	}
}
elsif ($Command eq "stop")
{
	print "Stopping Super Tux Kart process...\n";
	system("touch '$SUPERTUXKARTDIR/nostart'");
	if ($running ne "")
	{
		# Process is running, kill it
		system("killall supertuxkart");
	}
}
elsif ($Command eq "restart")
{
	if (-f "$SUPERTUXKARTDIR/nostart")
	{
		print("Removing $SUPERTUXKARTDIR/nostart\n");
		unlink("$SUPERTUXKARTDIR/nostart");
	}
	if ($running ne "")
	{
		system("killall supertuxkart");
	}
}
elsif ($Command eq "status")
{
	if ($running ne "")
	{
		print("Super Tux Kart Server Running\n");
	}
	else
	{
		print("Super Tux Kart Server Not Running\n");
	}
}
else
{
	print ("Uknown command '$Command'\n");
	print ("Usage: $0 {start|status|stop|restart}\n");
	exit(1);
}

exit(0);
